export interface About {
  title: string
  content: string
}

export const about: About = {
  "title": "About",
  "content": "<p><em>Hey there,</em></p>\n<p>My name is Alice—<br>I&#39;m an independent musician, artist, author, and developer based out of the DMV areas.</p>\n<p>I release music underneath the alias, <a href=\"https://open.spotify.com/artist/4M8EnFxggAM0jWTedB5Qer?si=HYn9IqzpR_2Pkg1SLAmMiA\">freya langley.</a><br>And have been, for just about a decade now — <a href=\"https://soundcloud.com/atimetowait\">Soundcloud</a> is where you can find demos from throughout the years.</p>\n<p>I strive to have a philosophy of &quot;Don&#39;t think, just upload.&quot; — When it comes to creating art.<br>The same applies to developer work, such as this site. Much is unfinished, messy, and out of sorts...stuck in my own mental purgatory for the time being.<br>There&#39;s nobility in sharing the ins and outs of your process, workflow. Creative mishaps and success. </p>\n<p>Build in public.<br>Share with the void, sometimes...it speaks back.</p>\n<p>Alongside music,<br>I also write a novel named <a href=\"https://www.atimetowait.com/this-bias-is-beginning-to-show\">This Bias is Beginning to Show.</a><br>It&#39;s written through the lens of an autobiographical fiction. One partially following mine, and the character of Astoria&#39;s life.<br>You&#39;ll find themes of grief, mortality, and hopefully a comfort in even through decay more of <em>you</em> can lie underneath...whatever it is we are, that is.<br>It is still a very much &quot;work in progress&quot; moment as well, you&#39;ll find frequent updates. Things never staying the same, and add-ons sporadically throughout the night.</p>\n<p>Stll, it is something I hope you enjoy :)</p>\n<p>Reach out with any thoughts in your head, send me a note anonymously via <a href=\"https://www.atimetowait.com/whats-your-name\">What&#39;s Your Name?</a><br>Or simply email me via <a href=\"mailto:atimetowait@gmail.com\">atimetowait@gmail.com</a><br>There&#39;s never such a thing as a stranger...be well.<br>xoxo</p>\n<p>-alice</p>\n"
}
