export interface Note {
  slug: string
  title: string
  date: string
  excerpt: string
  content: string
}

export const notes: Note[] = [
  {
    "slug": "asdeepasitistall",
    "title": "As deep as it is tall",
    "date": "2025",
    "excerpt": "",
    "content": "<p>It's still there, right here actually.  Beaming in my chest—refracted light. With it, the moths seem to do all they can to see who'll shrivel up first. But deeper in cavities, there lay a thread. Ever so small, but still as deep as it is tall. This thread, it…calls to you. To a pattern that's unknown in form but with ecstasy it erupts. I didn't know what to do with it either. I didn't heed the calls, or answer the prayers—let alone, look it in its eyes when it spoke to me. For me, it knows every scent.</p>\n<p>Maybe you saw her first though? Caught a glimpse between the lines, between the letters? Like a ghost in the mirror. A ghost in the wings?</p>\n<p>Like sirens, entrenching weight follows each tone. Enough to keep my head below the surface level.  Deep breathes in and out of clarity help. Though the undertow unravels all, it'll even make a warrior out of you, promise it your secrets too—you don't have anything to hide still…do you?  Speak. Or,</p>\n<p>Forever hold your peace.</p>\n<p>I laid there in the dark for some while.  I thought indifference couldn't follow me here. I thought black didn't fade to gray, I thought I'd never lose my footing. I thought—</p>\n<p>That's all I'll ever do is think.  Think, for what exactly? To rebuttal an already exposed sore? All you can do is hurt, but watch them break down the grease, then, trust. It was never meant to hold you this close yet, you're still in its wake. The knowledge is comforting, and what lingers inside of you is foreboding—an instinctual nature that lie deep in those wounds.</p>\n<p>To weep or not is more worrying than the onset of tears. The last thing on your face before death, the last thing on your mind. What are you thinking? Do you even think, in a moment like that? Are you thinking right now? And why is that bothersome, or burdensome? Even worse, worrisome.  Because the more you worry, the more it drills farther into this husk, a husk with bones. A husk with feelings, that need reminded of life, and not death. Not superficial crystals, or inescapable dialogues with people who wouldn't dare dip their toes into your tepid waters. But climax, and to be displayed like a figurine. I want bullets with no exit wounds, depth with no drowning, nothing to bring me back to something. I'll watch the world relapse, I'll cherish a fleeting breath, I'll love just a little harder so that when I shout your name it wouldn't dare return back an echo, for there can be no other alter. I'd lay with my peace, and count til three.</p>\n<p>Suddenly there's the bell, how it chimes is unrecognizable now but I still feel the vibrations in my chest that remind me—it's home.  I wallow in my slowness for a bit. I wallow a fair bit, actually. Mainly with reminiscence towards the past, and towards this present I wouldn't dare predict. There are school kids that run around again, and still, I can find home wherever I see fit.</p>"
  },
  {
    "slug": "remarkable",
    "title": "There is something inside of you that is remarkable",
    "date": "October 2025",
    "excerpt": "",
    "content": "<p>Lately I've been needing things—anything, one…to hold onto.  I've been worried about the state of myself for months now. It's sinister to have to stand aside, and watch as something fails inside you. But to understand yourself, that may be the only thing you can do. To get to the next step, phase, plan, path—whatever is inside of you, it is something remarkable.</p>\n<p>A practice I fell in love with this year is remastering my old songs, tossing and turning them sonically to fit not only today's standards, but new ones I find myself never knowing I'd have. It's a beautiful thing to hear a 5-6 year old song have new breaths in them. To pick up on the details I didn't even know I put in, to hear a soundstage that roars beneath it all. It's beautiful, Maybe I am too.</p>\n<p>I think losing yourself is a beautiful thing too. As to lose is to have to seek—is to have to find, is to finally piece something together correctly, for once. It's in the inertia, the bearings that make us up. Don't those need proper care? Lubricant? Maybe just a push—or shove in the right direction.  I've always found meaning in struggle, and it's different when things become easy. You can form habits there, yourself may even lay there too. And after, may just be continuation. One foot in front of the other, resistance to old ways, a better tomorrow always starts—new.</p>\n<p>Whatever is inside of you—a fluidity to cave towards spasmodic weight, beliefs of betterment from words that are atonal still, or a foundation that needs just water…and time, as it billows up inside of you, it becomes more of you. So let it, Let it happen, Let you succumb to flashes of an aura.</p>\n<p>One that you didn't know could sing so softly,</p>\n<p>One that you didn't know was just—you</p>\n<p>All along.</p>"
  }
]
